services:
    Ibexa\Test\Rest\Schema\Validator\SchemaValidatorRegistry:
        public: true
        arguments:
            $validators: !tagged_iterator { tag: ibexa.test.rest.schema.validator, index_by: format }

    Ibexa\Test\Rest\Schema\Validator\BaseSchemaValidator: ~

    Ibexa\Test\Rest\Schema\Validator\JsonSchemaValidator:
        parent: Ibexa\Test\Rest\Schema\Validator\BaseSchemaValidator
        arguments:
            $validator: '@ibexa.test.rest.json_schema.validator'
        tags:
            - { name: ibexa.test.rest.schema.validator, format: json }

    Ibexa\Test\Rest\Schema\Validator\XmlSchemaValidator:
        parent: Ibexa\Test\Rest\Schema\Validator\BaseSchemaValidator
        tags:
            - { name: ibexa.test.rest.schema.validator, format: xml }

    ibexa.test.rest.json_schema.validator:
        class: JsonSchema\Validator
        public: true
        arguments:
            $factory: '@ibexa.test.rest.json_schema.factory'

    ibexa.test.rest.json_schema.factory:
        class: JsonSchema\Constraints\Factory
        arguments:
            $schemaStorage: '@ibexa.test.rest.json_schema.schema_storage'

    ibexa.test.rest.json_schema.schema_storage:
        class: JsonSchema\SchemaStorage
        public: true
        arguments:
            $uriRetriever: '@ibexa.test.rest.json_schema.uri_retriever'

    ibexa.test.rest.json_schema.uri_retriever:
        class: JsonSchema\Uri\UriRetriever
